# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MapOutdoorTest' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
    use_frameworks!
    pod 'GoogleMaps', '= 3.7.0'
    pod 'GooglePlaces', '= 3.7.0'
    pod 'SwiftProtobuf', '~> 1.12.0'

  target 'MapOutdoorTestTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MapOutdoorTestUITests' do
    # Pods for testing
  end

end
